server:
  port: 3000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xiaomi?characterEncoding=UTF8
    username: root
    password: mysql123
  redis:
    host: localhost
  rabbitmq:
    host: localhost
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapUnderscoreToCamelCase: true